export const SELECT_LOGIN_REQUEST = 'SELECT_LOGIN_REQUEST';
export const SELECT_LOGIN_SUCCESS = 'SELECT_LOGIN_SUCCESS';
export const SELECT_LOGIN_FAILURE = 'SELECT_LOGIN_FAILURE';

export const SELECT_INDEX_REQUEST = 'SELECT_INDEX_REQUEST';
export const SELECT_INDEX_SUCCESS = 'SELECT_INDEX_SUCCESS';
export const SELECT_INDEX_FAILURE = 'SELECT_INDEX_FAILURE';

export const SELECT_ORDER_REQUEST = 'SELECT_ORDER_REQUEST';
export const SELECT_ORDER_SUCCESS = 'SELECT_ORDER_SUCCESS';
export const SELECT_ORDER_FAILURE = 'SELECT_ORDER_FAILURE';
export const SELECT_ORDER_REPLACE = 'SELECT_ORDER_REPLACE';

export const UPDATE_REFUND_REQUEST = 'UPDATE_REFUND_REQUEST';
export const UPDATE_REFUND_SUCCESS = 'UPDATE_REFUND_SUCCESS';
export const UPDATE_REFUND_FAILURE = 'UPDATE_REFUND_FAILURE';
export const UPDATE_REFUND_REPLACE = 'UPDATE_REFUND_REPLACE';

export const INSERT_LOAN_REQUEST = 'INSERT_LOAN_REQUEST';
export const INSERT_LOAN_SUCCESS = 'INSERT_LOAN_SUCCESS';
export const INSERT_LOAN_FAILURE = 'INSERT_LOAN_FAILURE';

export const SELECT_USER_REQUEST = 'SELECT_USER_REQUEST';
export const SELECT_USER_SUCCESS = 'SELECT_USER_SUCCESS';
export const SELECT_USER_FAILURE = 'SELECT_USER_FAILURE';

export const SELECT_DETAIL_REQUEST = 'SELECT_DETAIL_REQUEST';
export const SELECT_DETAIL_SUCCESS = 'SELECT_DETAIL_SUCCESS';
export const SELECT_DETAIL_FAILURE = 'SELECT_DETAIL_FAILURE';

export const INSERT_SUGGEST_REQUEST = 'INSERT_SUGGEST_REQUEST';
export const INSERT_SUGGEST_SUCCESS = 'INSERT_SUGGEST_SUCCESS';
export const INSERT_SUGGEST_FAILURE = 'INSERT_SUGGEST_FAILURE';

export const INSERT_PAYMENT_REQUEST = 'INSERT_PAYMENT_REQUEST';
export const INSERT_PAYMENT_SUCCESS = 'INSERT_PAYMENT_SUCCESS';
export const INSERT_PAYMENT_FAILURE = 'INSERT_PAYMENT_FAILURE';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';