export const SELECT_LOGIN_REQUEST = 'SELECT_LOGIN_REQUEST';
export const SELECT_LOGIN_SUCCESS = 'SELECT_LOGIN_SUCCESS';
export const SELECT_LOGIN_FAILURE = 'SELECT_LOGIN_FAILURE';

export const SELECT_INDEX_REQUEST = 'SELECT_INDEX_REQUEST';
export const SELECT_INDEX_SUCCESS = 'SELECT_INDEX_SUCCESS';
export const SELECT_INDEX_FAILURE = 'SELECT_INDEX_FAILURE';